import { getLocale } from "next-intl/server";
import type { Locale } from "@/i18n/config";
import { LegalShell } from "@/components/legal/legal-shell";

export const metadata = {
  title: "Politika privatnosti - ProcureLink",
  description:
    "Kako ProcureLink prikuplja i obrađuje podatke (GDPR i Zakon o zaštiti podataka o ličnosti).",
};

// NOTE FOR FOUNDER: replace the bracketed placeholders with your registered
// entity details before public launch (controller identity, PIB, address) and
// confirm the contact addresses. Have a Serbian lawyer review before charging.
const CONTROLLER = "[Naziv pravnog lica d.o.o., PIB, adresa u Srbiji]";
const PRIVACY_EMAIL = "privatnost@procure-link.com";

export default async function PrivacyPage() {
  const locale = (await getLocale()) as Locale;
  const sr = locale === "sr";

  return (
    <LegalShell
      title={sr ? "Politika privatnosti" : "Privacy Policy"}
      subtitle={
        sr
          ? "Kako prikupljamo i obrađujemo podatke u skladu sa GDPR-om i Zakonom o zaštiti podataka o ličnosti (ZZPL)."
          : "How we collect and process data under the GDPR and Serbia's Personal Data Protection Act (ZZPL)."
      }
      backLabel={sr ? "Nazad na početnu" : "Back to home"}
      lastUpdated={sr ? "Poslednje ažuriranje: jun 2026." : "Last updated: June 2026"}
    >
      {sr ? (
        <>
          <section>
            <h2>Rukovalac podacima</h2>
            <p>
              Rukovalac je {CONTROLLER}. ProcureLink je B2B platforma koja povezuje
              restorane i dobavljače. Za sva pitanja o privatnosti pišite na{" "}
              <a href={`mailto:${PRIVACY_EMAIL}`}>{PRIVACY_EMAIL}</a>.
            </p>
          </section>
          <section>
            <h2>Koje podatke prikupljamo</h2>
            <p>
              Prilikom registracije prikupljamo poslovne kontakt podatke: ime i
              prezime, poslovni imejl, naziv i adresu firme, telefon, kao i podatke
              o proizvodima i porudžbinama nastale korišćenjem platforme. Ne
              prikupljamo podatke o ličnosti više nego što je neophodno za vođenje
              poslovnog naloga.
            </p>
          </section>
          <section>
            <h2>Pravni osnov i svrha</h2>
            <p>
              Podatke obrađujemo radi izvršenja ugovora (pružanje usluge ProcureLink),
              u skladu sa članom 6. GDPR-a i odgovarajućim odredbama ZZPL-a. Podatke
              ne prodajemo trećim licima i ne koristimo ih za oglašavanje.
            </p>
          </section>
          <section>
            <h2>Obrađivači</h2>
            <p>Za rad platforme koristimo sledeće obrađivače:</p>
            <ul>
              <li>Supabase (baza i autentikacija, EU region)</li>
              <li>Vercel (hosting aplikacije)</li>
              <li>Resend (transakcioni imejl)</li>
              <li>Sentry (praćenje grešaka)</li>
              <li>Paddle (naplata - aktivira se kada uvedemo plaćanje)</li>
            </ul>
            <p>
              Sa svakim obrađivačem imamo ili zaključujemo ugovor o obradi podataka
              (DPA) u skladu sa članom 28. GDPR-a.
            </p>
          </section>
          <section>
            <h2>Čuvanje podataka</h2>
            <p>
              Podatke čuvamo dok je nalog aktivan i do 24 meseca nakon zatvaranja
              naloga, osim kada nas duži rok obavezuje (npr. poreski propisi).
            </p>
          </section>
          <section>
            <h2>Vaša prava</h2>
            <p>
              Imate pravo na pristup, ispravku, brisanje, ograničenje obrade i
              prenosivost podataka, kao i pravo na prigovor. Nalog i sve povezane
              podatke možete obrisati u podešavanjima ili slanjem zahteva na{" "}
              <a href={`mailto:${PRIVACY_EMAIL}`}>{PRIVACY_EMAIL}</a>. Pritužbu možete
              uputiti Povereniku za informacije od javnog značaja i zaštitu podataka
              o ličnosti.
            </p>
          </section>
        </>
      ) : (
        <>
          <section>
            <h2>Data controller</h2>
            <p>
              The controller is {CONTROLLER}. ProcureLink is a B2B platform connecting
              restaurants and suppliers. For any privacy question, email{" "}
              <a href={`mailto:${PRIVACY_EMAIL}`}>{PRIVACY_EMAIL}</a>.
            </p>
          </section>
          <section>
            <h2>What we collect</h2>
            <p>
              At registration we collect business contact data: full name, work email,
              company name and address, phone, and the product/order data generated by
              using the platform. We collect no more personal data than is necessary to
              run a business account.
            </p>
          </section>
          <section>
            <h2>Lawful basis and purpose</h2>
            <p>
              We process this data to perform our contract with you (providing the
              ProcureLink service), under Article 6 GDPR and the corresponding ZZPL
              provisions. We do not sell data or use it for advertising.
            </p>
          </section>
          <section>
            <h2>Processors</h2>
            <p>We use the following processors:</p>
            <ul>
              <li>Supabase (database and auth, EU region)</li>
              <li>Vercel (application hosting)</li>
              <li>Resend (transactional email)</li>
              <li>Sentry (error monitoring)</li>
              <li>Paddle (billing - activated when payments launch)</li>
            </ul>
            <p>
              We hold or are finalising an Article 28 GDPR data processing agreement
              (DPA) with each processor.
            </p>
          </section>
          <section>
            <h2>Retention</h2>
            <p>
              We keep data while the account is active and for up to 24 months after
              closure, unless a longer period is legally required (e.g. tax law).
            </p>
          </section>
          <section>
            <h2>Your rights</h2>
            <p>
              You have the right to access, rectify, erase, restrict and port your data,
              and to object. You can delete your account and all related data in settings
              or by emailing <a href={`mailto:${PRIVACY_EMAIL}`}>{PRIVACY_EMAIL}</a>. You
              may also lodge a complaint with the Serbian Commissioner for Information of
              Public Importance and Personal Data Protection.
            </p>
          </section>
        </>
      )}
    </LegalShell>
  );
}
